server.port=${PORT:8082}
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT:5432}/${PGDATABASE}?sslmode=disable
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null

management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=always

logging.level.com.gym=INFO
